sonar.projectKey=saalmi098-cdas
sonar.organization=saalmi098-cdas

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.sourceEncoding=UTF-8
